version: '3.1'

services:

  frontend:
    depends_on:
      - backend
    build: ./frontend/frontend
    ports:
      - 3000:3000

  backend:
    depends_on:
    - mysql
    build: ./backend/backend
    environment:
      - PORT_DB=3306
      - DB_NAME=Condominio
      - DB_ROOT=root
      - DB_PASS=root
      - DB_HOST=localhost
    ports:
      - 3001:3001

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: Condominio
    ports:
      - 3306:3306

